/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c9962e0b-0d22-44d0-9a36-edcf9ceadcd2",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_INH7XYmrl",
    "aws_user_pools_web_client_id": "4t7u17r8js9jjvbv2dp16k7rc7",
    "oauth": {},
    "aws_user_files_s3_bucket": "iheartcodechallengefe506ffdfb644a5d8fa0253c59c712706-dev",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "api7a0eff10",
            "endpoint": "https://qqdjnpwrqg.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
